<?php
/* @var $block \MW\DailyDeal\Block\Sidebar\ActiveDeal */
$isShowActiveDeal = $block->isShowActiveDeals();
if ($isShowActiveDeal) {
    $numberActive = $block->getNumberrActiveDeal();
    $activeDealsCollection = $block->getActiveDeals();
    $_collectionSize = count($activeDealsCollection);
    if ($_collectionSize > 0):
        $count = 0;
    ?>
    <?php $dld_color_title = $block->getConfigSchemeColor(); ?>
    <?php $dld_color_coundown = $block->getConfigCountdownColor(); ?>
    <?php $dld_color_lighight = $block->getConfigHighlightColor(); ?>
    <?php
    function colourBrightness_active($hex, $percent)
    {
        $hash = '';
        if (stristr($hex, '#')) {
            $hex = str_replace('#', '', $hex);
            $hash = '#';
        }
        /// HEX TO RGB
        $rgb = array(hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2)));
        //// CALCULATE
        for ($i=0; $i<3; $i++) {
            // See if brighter or darker
            if ($percent > 0) {
                // Lighter
                $rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
            } else {
                // Darker
                $positivePercent = $percent - ($percent*2);
                $rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
            }
            // In case rounding up causes us to go to 256
            if ($rgb[$i] > 255) {
                $rgb[$i] = 255;
            }
        }
        //// RBG to Hex
        $hex = '';
        for ($i=0; $i < 3; $i++) {
            // Convert the decimal digit to hex
            $hexDigit = dechex($rgb[$i]);
            // Add a leading zero if necessary
            if (strlen($hexDigit) == 1) {
                $hexDigit = "0" . $hexDigit;
            }
            // Append to the hex string
            $hex .= $hexDigit;
        }
        return $hash.$hex;
    }
    ?>

    <style type="text/css">
        .block-deals{ box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>; -moz-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>; -webkit-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>}
        .block-deals .block-title-act{ background-color: <?php echo $block->escapeHtml($dld_color_title); ?>; background-image: linear-gradient(to bottom, <?php echo colourBrightness_active($dld_color_title, 0.9);?>, <?php echo colourBrightness_active($dld_color_title, -0.7);?>); background-image: -webkit-linear-gradient(to bottom, <?php echo colourBrightness_active($dld_color_title, 0.9);?>, <?php echo colourBrightness_active($dld_color_title, -0.7);?>); background-image:    -moz-linear-gradient(to bottom, <?php echo colourBrightness_active($dld_color_title, 0.9);?>, <?php echo colourBrightness_active($dld_color_title, -0.7);?>);	background-image:     -ms-linear-gradient(to bottom, <?php echo colourBrightness_active($dld_color_title, 0.9);?>, <?php echo colourBrightness_active($dld_color_title, -0.7);?>); background-image:      -o-linear-gradient(to bottom, <?php echo colourBrightness_active($dld_color_title, 0.9);?>, <?php echo colourBrightness_active($dld_color_title, -0.7);?>);}
        .block-deals .block-content{background: <?php echo colourBrightness_active($dld_color_title, 0.1);?>}
        .block-deals li.odd{background: <?php echo colourBrightness_active($dld_color_title, 0.1);?>}
        .block-deals .block-content p.product-name a{color: <?php echo colourBrightness_active($dld_color_title, -0.7);?>;}
        .block-deals .special-price .price{color: <?php echo $block->escapeHtml($dld_color_lighight);?>}
        .dailydeal-qty-box .deal-qty{color: <?php echo $block->escapeHtml($dld_color_lighight);?>}
        .block-deals .actions a{color: <?php echo $block->escapeHtml($dld_color_title); ?>;}
        .block-deals button.button span{background: <?php echo $dld_color_title; ?>; border: 1px solid <?php echo $block->escapeHtml($dld_color_title); ?>;}
        .block-deals button.button span span{background: none; border: 0px none;}
        .block-deals{border: 1px solid <?php echo $block->escapeHtml($dld_color_title); ?>;}
    </style>
    <div class="block block-deals" >
        <div class="block-title-act">
            <strong><span><?php echo $block->escapeHtml(__('Active Deals')); ?></span></strong>
        </div>
        <div class="block-content">
            <ol id="recently-viewed-items" class="mini-products-list">
                <?php
                foreach ($activeDealsCollection as $activeDeal) {
                    /* @var $activeDeal \MW\DailyDeal\Model\Dailydeal */
                    $dealQty = $activeDeal->getDealQty();
                    $soldQty = $activeDeal->getSoldQty();
                    $product = $block->getProductById($activeDeal->getProductId());
                    ?>
                    <?php if ($count != $numberActive) { ?>
                        <li class="item">
                            <p class="product-name">
                                <a href="<?php echo $block->escapeHtml($product->getProductUrl()) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>">
                                    <?php echo $block->escapeHtml($product->getName()) ?>
                                </a>
                            </p>
                            <a href="<?php echo $block->escapeHtml($product->getProductUrl()) ?>"
                               title="<?php echo $block->escapeHtml($product->getName()); ?>" class="product-image">
                                <img src="<?php echo $block->escapeHtml($block->getProductImageUrl($product)); ?>" width="70" height="70"
                                     alt="<?php echo $block->escapeHtml($product->getName()); ?>" />
                            </a>
                            <div class="product-details">
                                <div class="price-box">

                                    <?php if ($activeDeal->checkDealPrice($product)) { ?>
                                        <?php $regularPrice = $product->getData('price') ?>
                                        <?php $finalPrice = $activeDeal->getDailydealPrice() ?>
                                        <p class="old-price">
                                            <span class="regular-price">
                                                <span class="old-price" style="text-decoration: line-through">
                                                    <?php echo $block->addPriceWithCurrency($regularPrice) ?>
                                                </span>
                                            </span>
                                        </p>
                                        <p class="special-price">
                                            <span class="price">
                                                <?php echo $block->addPriceWithCurrency($finalPrice) ?>
                                            </span>
                                        </p>

                                    <?php } else {
                                        $activeDeal->setMinPriceFollowProductType($product, $activeDeal);
                                        ?>
                                        <p class="from-price special-price">
                                            <span class="pri-label"><?php echo $block->escapeHtml(__('From'));?></span>
                                            <span class="price">
                                                <?php echo $block->addPriceWithCurrency($product->getData('min_price')) ?>
                                            </span>
                                        </p>
                                    <?php } ?>
                                </div>
                                <form data-role="tocart-form" action="<?php echo $block->getAddToCartUrl($product); ?>" method="post">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Buy now')) ?>"
                                            class="button btn-buynow action tocart primary">
                                        <span><?php echo $block->escapeHtml(__('Buy now')) ?></span>
                                    </button>
                                </form>
                            </div>
                            <div class="dailydeal-qty-box daily-qty-box-active">
                                <?php if ($activeDeal->checkDealQtyToShow($product) && $block->getConfigDisplayQuantity()) { ?>
                                    <?php
                                    if (($dealQty - $soldQty) > 10) {
                                        echo __('Hurry, just <span class="deal-qty">%1 items</span> available.', $dealQty - $soldQty);
                                    } elseif (($dealQty - $soldQty) <= 10 && ($dealQty - $soldQty) > 1) {
                                        echo __('Hurry, just <span class="deal-qty">%1 items</span> left!', $dealQty - $soldQty);
                                    } elseif (($dealQty - $soldQty) == 1) {
                                        echo __('Hurry, just <span class="deal-qty">%1 item</span> left!', $dealQty - $soldQty);
                                    }
                                    ?>
                                <?php } ?>
                            </div>
                        </li>
                        <?php $count++; ?>
                    <?php } ?>
                <?php } ?>
            </ol>
            <div class="actions">
                <a style="float: right;" href="<?php echo $block->getUrl('dailydeal/index/index'); ?>"><?php echo $block->escapeHtml(__('View all')); ?></a>
            </div>
        </div>
    </div>
<?php endif;
} ?>

