<?php
/* @var $block \MW\DailyDeal\Block\Sidebar\Calendar */
$isShowWeekDeals = $block->isShowWeekDeals();
if ($isShowWeekDeals) {
    $numberActive = $block->getNumberrActiveDeal();
    $title = $block->getConfigTodayDealBlockTitle();
?>
<?php
$arraydays = $block->getWeeklyDeal();
?>
<!--  anh san pham, ten san pham, gia cu, gia khuyen mai -->
    <script type="text/javascript">
        require(['jquery'],function($){
            $(window).load(function() {
                <?php
                for ($i = 0; $i < 7; $i++) { ?>
                    $("#cell-<?php echo $i ?>").hover(
                        function() {
                            $('#cell-value-<?php echo $i ?>').css( "display", "block" );
                            $('#cell-value-<?php echo $i ?>').css( "position", "absolute" );
                            $('#cell-value-<?php echo $i ?>').css( "z-index", "9999" );
                    }, function() {
                            $("#cell-value-<?php echo $i ?>").hover(
                                function() {
                                    $('#cell-value-<?php echo $i ?>').css( "display", "block" );
                                    $('#cell-value-<?php echo $i ?>').css( "background", "#fff" );
                                }, function() {
                                    $('#cell-value-<?php echo $i ?>').css('display', 'none');
                                });
                        $('#cell-value-<?php echo $i ?>').css('display', 'none');
                    });
                <?php } ?>
            });
        });
</script>
<link href="<?php echo $block->getAssetUrl('MW_DailyDeal::css/calendar.css'); ?>" type="text/css" rel="stylesheet" />
<link href="<?php echo $block->getAssetUrl('MW_DailyDeal::css/promo_group.css'); ?>" type="text/css" rel="stylesheet" />
<link href="<?php echo $block->getAssetUrl('MW_DailyDeal::css/tooltip/opentip.css'); ?>" type="text/css" rel="stylesheet" />

<script type="text/javascript">
    var anonymous = [];
    function hiddendeals(){
        for (k = 0; k< 7; k++){
            var idAno = document.getElementById('anonymous_element_'+k);
            if (idAno != null){
                //		Dung de remove luon id, de cho bo nho dem cua trang web ko chua qua n tag
                //		document.body.removeChild(idAno);
                //		Doi attibute cua 1 tag
                idAno.removeClassName('ot-completely-visible').addClassName('ot-completely-hidden');
            } else continue;
        }
    }
</script>

<?php $dld_color_title = $block->getConfigSchemeColor(); ?>
<?php $dld_color_coundown = $block->getConfigCountdownColor(); ?>
<?php $dld_color_lighight = $block->getConfigHighlightColor(); ?>
<?php
function colourBrightness_Cal($hex, $percent)
{
    $hash = '';
    if (stristr($hex, '#')) {
        $hex = str_replace('#', '', $hex);
        $hash = '#';
    }
    /// HEX TO RGB
    $rgb = array(hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2)));
    //// CALCULATE
    for ($i=0; $i<3; $i++) {
        // See if brighter or darker
        if ($percent > 0) {
            // Lighter
            $rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
        } else {
            // Darker
            $positivePercent = $percent - ($percent*2);
            $rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
        }
        // In case rounding up causes us to go to 256
        if ($rgb[$i] > 255) {
            $rgb[$i] = 255;
        }
    }
    //// RBG to Hex
    $hex = '';
    for ($i=0; $i < 3; $i++) {
        // Convert the decimal digit to hex
        $hexDigit = dechex($rgb[$i]);
        // Add a leading zero if necessary
        if (strlen($hexDigit) == 1) {
            $hexDigit = "0" . $hexDigit;
        }
        // Append to the hex string
        $hex .= $hexDigit;
    }
    return $hash.$hex;
}
?>

<style type="text/css">
    .block-deals-cal{ box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>; -moz-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>; -webkit-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>}
    .block-deals-cal .block-title{ background-color: <?php echo $block->escapeHtml($dld_color_title); ?>; background-image: linear-gradient(to bottom, <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, 0.9));?>, <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, -0.7));?>);}
    .opentip{box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>;}
    .ot-container .header{ background-color: <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, 0.9));?>; background-image: linear-gradient(to bottom, <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, 0.9));?>, <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, -0.7));?>);}
    .block-deals-week .block-content li.odd{background: <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, 0.1));?>}
    .block-deals-week .special-price .price{color: <?php echo $block->escapeHtml($dld_color_lighight);?>}
    table.doctable tbody td.select_deal{background:<?php echo $block->escapeHtml($dld_color_title); ?>}
    table.doctable tbody td.select_deal:hover{background:<?php echo $block->escapeHtml($dld_color_title); ?>}
    table.doctable tbody td.select_deal:hover span{background:<?php echo $block->escapeHtml($dld_color_title); ?>}
    table.doctable tbody td a{color:<?php echo $block->escapeHtml($dld_color_title); ?>}
    .block-deals-week .block-content p.product-name a{color: <?php echo $block->escapeHtml(colourBrightness_Cal($dld_color_title, -0.7));?>;}
</style>

<div id="blockcalendar" class="block-deals-cal">
    <div class="block-title">
        <strong><span><?php echo $block->escapeHtml('Deals of Week'); ?></span></strong>
    </div>
    <table class="doctable table"  >
        <tbody class="tbody">
        <tr>
            <?php
            $temp = [];
            $i = 0;
            $j = 0;
            $m = date('m', $block->date->scopeTimeStamp());
            $d = date('d', $block->date->scopeTimeStamp());
            $Y = date('Y', $block->date->scopeTimeStamp());
            while ($i<4) {
                $tomorrowshow = date('d-m', mktime( 0, 0, 0,$m, $d+$i, $Y));
                $textual = date('D', mktime(0, 0, 0,$m, $d+$i, $Y));
                $tomorrow = date('Y-m-d', mktime(0, 0, 0, $m, $d+$i, $Y));
                $template = $block->renderDealFollowDayHtml($tomorrow);
                ?>

                <?php if (in_array($tomorrow,$arraydays)) {
                    $temp[$j] = $i;$j++;
                } ?>

                <td <?php if (in_array($tomorrow, $arraydays)) echo 'class="select_deal"';?>>
                    <span id="cell-<?php echo $i;?>" ><?php echo $tomorrowshow.' '.$textual;?></span>
                    <span id="cell-value-<?php echo $i;?>" style="display:none"><?php echo $block->renderDealFollowDayHtml($tomorrow) ?></span>
                </td>

                <?php
                $i++;
            }
            ?>

        </tr>
        <tr>
            <?php
            while ($i<7) {
                $tomorrowshow = date('d-m', mktime(0, 0, 0, date('m'), date('d')+$i, date("Y")));
                $textual = date('D', mktime(0, 0, 0, date('m'), date('d')+$i, date("Y")));
                $tomorrow = date('Y-m-d', mktime(0, 0, 0, $m, $d+$i, $Y));
                ?>
                <?php if (in_array($tomorrow, $arraydays)) {
                    $temp[$j] = $i;$j++;
                } ?>
                <td id="<?php echo $i;?>" <?php if (in_array($tomorrow, $arraydays)) echo 'class="select_deal"'?>>
                    <span id="cell-<?php echo $i;?>" ><?php echo $tomorrowshow.' '.$textual;?></span>
                    <span id="cell-value-<?php echo $i;?>" style="display:none"><?php echo $block->renderDealFollowDayHtml($tomorrow) ?></span>
                </td>
                <?php
                $i++;
            }
            ?>
            <td id="cell_more" style="border: 2px solid white; ">
                <a href="<?php echo $block->escapeUrl($block->getUrl('dailydeal/index/index')); ?>"><?php echo $block->escapeHtml(__('More')); ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<?php }?>
