<?php $_product = $this->getData('product'); ?>
<?php
/**
 * @var $blockList \MW\DailyDeal\Block\Showtabs\ListDeal
 */
$blockList = $this->getLayout()->createBlock('MW\DailyDeal\Block\Showtabs\ListDeal');
if ($blockList->moduleEnable()) {
    /**
     * @var $_deal \MW\DailyDeal\Model\Dailydeal
     */
    $_deal = $blockList->loadDealActiveByProductId($_product->getId());
    $currentTime = $blockList->getTimeStamp();
    $dld_color_title = $blockList->getConfigSchemeColor();
    $dld_color_coundown = $blockList->getConfigCountdownColor();
    $dld_color_lighight = $blockList->getConfigHighlightColor();
    if (!function_exists('colourBrightnesscate_cl')) {
        function colourBrightnesscate_cl($hex, $percent)
        {
            $hash = '';
            if (stristr($hex,'#')) {
                $hex = str_replace('#','',$hex);
                $hash = '#';
            }
            /// HEX TO RGB
            $rgb = array(hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2)));
            //// CALCULATE
            for ($i=0; $i<3; $i++) {
                // See if brighter or darker
                if ($percent > 0) {
                    // Lighter
                    $rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
                } else {
                    // Darker
                    $positivePercent = $percent - ($percent*2);
                    $rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
                }
                // In case rounding up causes us to go to 256
                if ($rgb[$i] > 255) {
                    $rgb[$i] = 255;
                }
            }
            //// RBG to Hex
            $hex = '';
            for ($i=0; $i < 3; $i++) {
                // Convert the decimal digit to hex
                $hexDigit = dechex($rgb[$i]);
                // Add a leading zero if necessary
                if (strlen($hexDigit) == 1) {
                    $hexDigit = "0" . $hexDigit;
                }
                // Append to the hex string
                $hex .= $hexDigit;
            }
            return $hash.$hex;
        }
    }
    $lightcolor = colourBrightnesscate_cl($dld_color_title, 0.1);
    if ($_deal) {
        $blockList->increateFeaturedView($_deal->getId());
    ?>
        <style type="text/css">
            .mwdld_category div.counter ul li div.countdown_num{/*color: <?php //echo $dld_color_lighight?>; */
                background: <?php echo $blockList->escapeHtml($dld_color_coundown); ?>;
                width: 20px;
                height: 26px;
            }
            .mwdld_mess_cate span.deal-qty{color: <?php echo $blockList->escapeHtml($dld_color_lighight) ?>;}
            .mwdld_category{border-bottom: 1px dotted <?php echo $blockList->escapeHtml($dld_color_title) ?>;
                border-top: 1px dotted <?php echo $blockList->escapeHtml($dld_color_title) ?>;
                background: <?php echo $blockList->escapeHtml($lightcolor);?>;

            .mwdld_category{border: 1px solid <?php echo $blockList->escapeHtml($dld_color_title); ?>;}
            .products-grid .mwdld_category .counter ul li div.lb_time{font-size: 9px;}
        </style>
    <div class="mwdld_display_cate">
        <?php
        // show image
        if ($blockList->getConfigIsShowImageCatalogList()) {
            try {
                $url = $blockList->helperDailyDeal->getUrlImageCatalogList();
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                echo $blockList->escapeHtml($e);
            }
            ?>

            <img class="mwdld_img_sale" src="<?php echo $blockList->escapeUrl($url) ?>"
                 alt="<?php echo __('sale'); ?>"/>
            <?php if ($blockList->getConfigUseCustomLableDiscount()) {?>
            <strong><div class="mw_dd_centered"><?php echo $blockList->escapeHtml($_deal->getDiscount())?>%</div></strong>
        <?php   }
        } ?>

        <div class="mwdld_category">
            <div id="counter" class="counter">
                <ul class="countdown">
                    <li class="first">
                        <div class="countdown_num" id="ct_day-<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div>
                        <div class="lb_time" id="lb_ct_day<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div></li>
                    <li>
                        <div class="countdown_num" id="ct_hour-<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div>
                        <div class="lb_time" id="lb_ct_hour<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div></li>
                    <li>
                        <div class="countdown_num" id="ct_min-<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div>
                        <div class="lb_time" id="lb_ct_minute<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div></li>
                    <li class="last">
                        <div class="countdown_num" id="ct_sec-<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div>
                        <div class="lb_time" id="lb_ct_second<?php echo $blockList->escapeHtml($_deal->getId()) ?>"></div></li>
                </ul>
                <div class="clear"><span>&nbsp;</span></div>
            </div>

            <div class="mwdld_mess_cate">
                <?php
                $dealqty = $_deal->getDealQty();
                $soldqty = $_deal->getSoldQty();

                ?>
                <?php if ($blockList->getConfigDisplayQuantity()) { ?>
                    <?php
                    if (($dealqty - $soldqty) > 10) {
                        echo $blockList->helperDailyDeal->renderDealQtyOnCatalogPage($dealqty - $soldqty);
                    } elseif (($dealqty - $soldqty) <= 10 && ($dealqty - $soldqty) > 1) {
                        echo $blockList->helperDailyDeal->renderDealQtyOnCatalogPage($dealqty - $soldqty);
                    } elseif (($dealqty - $soldqty) == 1) {
                        echo $blockList->helperDailyDeal->renderDealQtyOnCatalogPage($dealqty - $soldqty);
                    }
                    ?>
                <?php } ?>
            </div>
        </div>
        <?php
        $startTime =  date('d M Y H:i:s', strtotime($_deal->getStartDateTime()));
        $endTime =  date('d M Y H:i:s', strtotime($_deal->getEndDateTime()));
        $remain_second = strtotime($endTime) - $currentTime;
        ?>

        <script type="text/javascript">
            var todaydeal_server_time = {
                second: <?php echo $remain_second; ?>,
                callback: '',

                id_day  : 'ct_day-' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                id_hour  : 'ct_hour-' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                id_minute  : 'ct_min-' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                id_second  : 'ct_sec-' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,

                label_day : 'lb_ct_day' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                label_hour : 'lb_ct_hour' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                label_minute : 'lb_ct_minute' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,
                label_second : 'lb_ct_second' + <?php echo $blockList->escapeHtml($_deal->getId()); ?>,

                label_day_value : '<?php echo __('Day'); ?>',
                label_hour_value : '<?php echo __('Hours'); ?>',
                label_minute_value : '<?php echo __('Mins'); ?>',
                label_second_value : '<?php echo __('Secs'); ?>'
            };

            countDownSecond(todaydeal_server_time);
        </script>
    </div>
<?php   }
} ?>
