<?php
/** @var \MW\DailyDeal\Block\ProductPage $block */
$_product = $block->getCurrentProduct();
/** @var \MW\DailyDeal\Model\Dailydeal $_deal */
$_deal = $block->getDeals($_product);

$title = '';
if ($_deal) {
    $title = $block->getProductDetailLabel();
    $startTime = date('Y-m-d H:i:s', strtotime($_deal->getStartDateTime()));
    $endTime = date('Y-m-d H:i:s', strtotime($_deal->getEndDateTime()));
    $currentTime = $block->getCurrentTime();
    $remain_second = strtotime($endTime) - $currentTime;
    $dealqty = $_deal->getDealQty();
    $soldqty = $_deal->getSoldQty();

    $dld_color_title = $block->getConfigSchemeColor();
    $dld_color_coundown = $block->getConfigCountdownColor();
    $dld_color_lighight = $block->getConfigHighlightColor();
    function colourBrightness_detail($hex, $percent)
    {
        $hash = '';
        if (stristr($hex, '#')) {
            $hex = str_replace('#', '', $hex);
            $hash = '#';
        }
        /// HEX TO RGB
        $rgb = array(hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2)));
        //// CALCULATE
        for ($i=0; $i<3; $i++) {
            // See if brighter or darker
            if ($percent > 0) {
                // Lighter
                $rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
            } else {
                // Darker
                $positivePercent = $percent - ($percent*2);
                $rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
            }
            // In case rounding up causes us to go to 256
            if ($rgb[$i] > 255) {
                $rgb[$i] = 255;
            }
        }
        //// RBG to Hex
        $hex = '';
        for ($i=0; $i < 3; $i++) {
            // Convert the decimal digit to hex
            $hexDigit = dechex($rgb[$i]);
            // Add a leading zero if necessary
            if (strlen($hexDigit) == 1) {
                $hexDigit = "0" . $hexDigit;
            }
            // Append to the hex string
            $hex .= $hexDigit;
        }
        return $hash.$hex;
    }
    ?>

    <style type="text/css">
        .deal-product{box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>;
            -moz-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>;
            -webkit-box-shadow: 0 0 3px <?php echo $block->escapeHtml($dld_color_title); ?>
        }
        .deal-product .catalogproductview{background-color: <?php echo $block->escapeHtml($dld_color_title); ?>;
            background-image: linear-gradient(to bottom,
            <?php echo colourBrightness_detail($dld_color_title, 0.9);?>,
            <?php echo colourBrightness_detail($dld_color_title, -0.7);?>);
        }
        .qty-deal{background: <?php echo colourBrightness_detail($dld_color_title, 0.1);?>}
        /*.counter ul.countdown li div.countdown_num span{background: */<?php //echo $dld_color_coundown; ?>/*}*/
        .counter ul.countdown li div.countdown_num{background: <?php echo $block->escapeHtml($dld_color_coundown); ?>}
        .qty-deal span.deal-qty{color: <?php echo $block->escapeHtml($dld_color_lighight);?>}
        .mw_dld_detail ul li span.mw_dld_detail_num{color: <?php echo $block->escapeHtml($dld_color_lighight);?>}
        .deal-product{border: 1px solid <?php echo $block->escapeHtml($dld_color_title); ?>;}

        .qty-deal div.mw_dd_description{
            color: <?php echo $block->escapeHtml($dld_color_lighight); ?>;
        }
    </style>

    <div class="deal-product">
        <div class="catalogproductview">
            <?php if ($title == '') { ?>
                <h3><?php echo __('Get it before it&acute;s gone!'); ?></h3>
            <?php } else { ?>
                <h3><?php echo $block->escapeHtml($title); ?></h3>
            <?php } ?>
        </div>
        <div class="ct-deal-pro">
            <!-- Countdown Javascript -->
            <div id="counter" class="counter">
                <ul class="countdown">
                    <li class="first">
                        <div class="countdown_num" id="lp_day-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                        <div id="lbl_lp_day-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                    </li>
                    <li>
                        <div class="countdown_num" id="lp_hour-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                        <div id="lbl_lp_hour-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                    </li>
                    <li>
                        <div class="countdown_num" id="lp_minute-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                        <div id="lbl_lp_minute-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                    </li>
                    <li class="last">
                        <div class="countdown_num" id="lp_second-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                        <div id="lbl_lp_second-<?php echo $block->escapeHtml($_deal->getId()) ?>"></div>
                    </li>
                </ul>
            </div>
            <div id="expired" style="display:none;">
                <?php __('The deadline has passed.'); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var todaydeal_server_time = {
            second: <?php echo $remain_second; ?>,
            callback: '',

            id_day: 'lp_day-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            id_hour: 'lp_hour-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            id_minute: 'lp_minute-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            id_second: 'lp_second-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,

            label_day: 'lbl_lp_day-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            label_hour: 'lbl_lp_hour-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            label_minute: 'lbl_lp_minute-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,
            label_second: 'lbl_lp_second-' + <?php echo $block->escapeHtml($_deal->getId()); ?>,

            label_day_value: '<?php //echo __('d') ?>',
            label_hour_value: '<?php //echo __('h') ?>',
            label_minute_value: '<?php //echo __('m') ?>',
            label_second_value: '<?php //echo __('s') ?>'
        };
        require([
            'jquery'
        ], function () {
            countDownSecond(todaydeal_server_time);

            function dealTimeOut(dealId) {

                var urlpath = '<?php echo $this->getUrl('dailydeal/index/ajaxDeal') . '?dealId='; ?>' + dealId;
                // $.ajax.Request(urlpath, {
                //     method: "GET",
                //     onSuccess: function (resp) {
                //         alert("End Deal");
                //     }
                // });

                jQuery.ajax({
                    type : 'POST',
                    url  : urlpath,
                    data : dealId,
                    dataType: 'json',
                    success: function(data){
                        location.reload();
                    },
                    error: function(){
                        // location.reload();
                    }
                });
            }

            function countDownSecond(obj) {

                if (obj.second > 0) {
                    obj.second--;

                    setTimeout(function () {
                        if (obj.callback != '') {
                            obj.callback(obj);
                        } else {
                            showTime(obj);
                        }
                    }, 0);

                    setTimeout(function () {
                        countDownSecond(obj);
                    }, 1000);
                }
                if (obj.second == 0) {
                    var dealId = <?php echo $block->escapeHtml($_deal->getId()); ?>;
                    dealTimeOut(dealId);
                    return;
                }
            }

            function showTime(obj) {

                var seconds = Math.floor(obj.second);
                var minutes = Math.floor(seconds / 60);
                var hours = Math.floor(minutes / 60);
                var days = Math.floor(hours / 24);

                hours %= 24;
                minutes %= 60;
                seconds %= 60;

                var str_days = wrapperTagSpan(insertOneZero(days));
                var str_hours = wrapperTagSpan(insertOneZero(hours));
                var str_minutes = wrapperTagSpan(insertOneZero(minutes));
                var str_seconds = wrapperTagSpan(insertOneZero(seconds));

                if (jQuery('#' + obj.label_day)) {
                    if (obj.label_day_value) {
                        jQuery('#' + obj.label_day).text(obj.label_day_value);
                    } else {
                        jQuery('#' + obj.label_day).text('<?php echo __('Days'); ?>');
                    }
                }
                if (jQuery('#' + obj.label_hour)) {
                    if (obj.label_hour_value) {
                        jQuery('#' + obj.label_hour).text(obj.label_hour_value);
                    } else {
                        jQuery('#' + obj.label_hour).text('<?php echo __('Hours'); ?>');
                    }
                }
                if (jQuery('#' + obj.label_minute)) {
                    if (obj.label_minute_value) {
                        jQuery('#' + obj.label_minute).text(obj.label_minute_value);
                    } else {
                        jQuery('#' + obj.label_minute).text('<?php echo __('Minutes'); ?>');
                    }
                }
                if (jQuery('#' + obj.label_second)) {
                    if (obj.label_second_value) {
                        jQuery('#' + obj.label_second).text(obj.label_second_value);
                    } else {
                        jQuery('#' + obj.label_second).text('<?php echo __('Seconds'); ?>');
                    }
                }

                if (jQuery('#' + obj.id_day)) jQuery('#' + obj.id_day).text(str_days);
                if (jQuery('#' + obj.id_hour)) jQuery('#' + obj.id_hour).text(str_hours);
                if (jQuery('#' + obj.id_minute)) jQuery('#' + obj.id_minute).text(str_minutes);
                if (jQuery('#' + obj.id_second)) jQuery('#' + obj.id_second).text(str_seconds);

                if (days <= 0) {
                    if (jQuery('#' + obj.label_day)) jQuery('#' + obj.label_day).text('');
                    if (jQuery('#' + obj.label_day)) jQuery('#' + obj.label_day).hide();
                    if (jQuery('#' + obj.id_day)) jQuery('#' + obj.id_day).text('');
                    if (jQuery('#' + obj.id_day)) jQuery('#' + obj.id_day).hide();
                }
            }

            function insertOneZero(value) {
                var result = '';

                if (value < 10) {
                    result += '0' + value;
                } else {
                    result += value;
                }

                return result;
            }

            function wrapperTagSpan(string) {
                var result = '';

                string.toString();

                for (var i = 0; i < string.length; i++) {
                    result += "" + string.charAt(i) + "";
                }

                return result;
            }
        });
    </script>
    <div class="clear"><span>&nbsp;</span></div>
    <?php if ($_deal->checkDealQtyToShow($_product) && ( $block->getConfigTodayDealShowDetail() || $block->getConfigDisplayQuantity())) { ?>
        <div class="qty-deal">

            <?php if ($block->getConfigTodayDealShowDetail()) {
                $_deal->processValueDiscountSaveBought(array('model_product' => $_product));
                $_deal_info = $_deal->getData('value_discount_save_bought');
                ?>
                <div class="mw_dld_detail">
                    <ul>
                        <li>
                            <span><?php echo __('Discount') ?></span>
                            <span class="mw_dld_detail_num"><?php echo $block->escapeHtml($_deal_info['discount']) ?></span>
                        </li>
                        <?php if (array_key_exists('you_save', $_deal_info)) { ?>
                        <li>
                            <span><?php echo __('You Save') ?></span>
                            <span class="mw_dld_detail_num"><?php echo $block->escapeHtml($_deal_info['you_save']) ?></span>
                        </li>
                        <?php } ?>
                        <li>
                            <span><?php echo __('Bought') ?></span>
                            <span class="mw_dld_detail_num"><?php echo $block->escapeHtml($_deal_info['bought']) ?></span>
                        </li>
                    </ul>
                </div>
            <?php } ?>

            <?php if ($block->getConfigDisplayQuantity()) { ?>
                <span>
                <?php
                    if (($dealqty - $soldqty) > 10) {
                        echo $block->escapeHtml($block->renderDealQtyOnProductPage($dealqty - $soldqty));
                    } elseif (($dealqty - $soldqty) <= 10 && ($dealqty - $soldqty) > 1) {
                        echo $block->escapeHtml($block->renderDealQtyOnProductPage($dealqty - $soldqty));
                    } elseif (($dealqty - $soldqty) == 1) {
                        echo $block->escapeHtml($block->renderDealQtyOnProductPage($dealqty - $soldqty));
                    }
                ?>
                </span>
            <?php } ?>

            <?php if ($block->getConfigDisplayDescription()) {?>
                <div class="mw_dd_description">
                    <?php echo $block->escapeHtml($_deal->getData('description')); ?>
                </div>
            <?php }?>
        </div>
    <?php } ?>

<?php } ?>
